### ISSUE TITLE
[Feature Request] Unique Task Queue Names for samples

### ISSUE THREAD

**Issue by mrturck** [temporalio/samples-typescript#104]
### Is your feature request related to a problem? Please describe.

Some of the samples have the same task-queue name. This can result in non-obvious workflow failures where multiple workers are subscribed to a task queue, but do not have the proper workflows and activities registered to handle the task pulled from the queue.

### Describe the solution you'd like

Tihomir in slack suggested I open this issue to provide unique task queue names for each sample to prevent this error.

### Additional context

I have already created a new branch, added unique task queue names to each of the samples, and have tested each. I am unable to contribute due to permissions, but would be happy to do so.

**Comment by lorensr** [comment]
Sounds good! Can you push your branch to a fork and then open a PR?
