### ISSUE TITLE
[ Documentation request ]  Better workflowId generator

### ISSUE THREAD

**Issue by joebowbeer** [temporalio/samples-typescript#110]
# Brief description

I suggest _**not**_ using `random * 1000` to generate workflow IDs in the documentation and sample code. For example:

```JavaScript
workflowId: 'wf-id-' + Math.floor(Math.random() * 1000),
```

This appears in two samples and a blog:

* https://github.com/temporalio/samples-typescript/blob/main/hello-world/src/client.ts#L21
* https://github.com/temporalio/samples-typescript/blob/main/grpc-calls/src/client.ts#L5
* https://github.com/temporalio/documentation/blob/master/blog/2022-02-28-temporal-rest.md?plain=1#L57

In only one instance is there a disclaimer comment:

```JavaScript
// in practice, use a meaningful business id, eg customerId or transactionId
```

Note that these IDs are required to be unique among open workflow executions in the same namespace.

Calculating the odds of a collision is solving the generalized birthday problem. With 1000 IDs to choose from, there's a 50% chance of a collision after generating 38 IDs, and a greater than 99% chance of collision after generating 100 IDs. (Assuming `random` is random.)

#  Your recommended content

1. I think the disclaimer should always be present.
1. If an ID generator is used in these samples, I suggest using something better than `random * 1000`, as I expect this snippet will end up being copied further. Use NanoID, UUID, or similar? Or just `'my-business-id'`?

**Comment by sw-yx** [comment]
pretty much the only reason i was avoiding uuid was it looks long and kinda ugly in the UI :) mind the aesthetics.

**Comment by vkarpov15** [comment]
@joebowbeer thanks for the suggestion, I put in a PR to fix this using nanoid for this repo and [`crypto.randomUUID()`](https://nodejs.org/api/crypto.html#cryptorandomuuidoptions) for blog posts.
