### ISSUE TITLE
[Feature Request] Speed up project creation time

### ISSUE THREAD

**Issue by lorensr** [temporalio/samples-typescript#136]
### Is your feature request related to a problem? Please describe.

Slow speed of `time npx @temporalio/create@latest test -s hello-world`

### Describe the solution you'd like

In hello-world/, `time npm i --prefer-online` takes 8s with a package-lock and 19s without, on gigabit ethernet. So first step is add package-lock files to each sample? Anything we can do beyond that?

**Comment by vkarpov15** [comment]
The reason why I preferred to avoid a lockfile is to avoid merge conflicts - devs with different versions of npm tend to overwrite each other's lockfile changes in surprising ways. However, performance is more important because ideally devs will be creating new projects more often than they'll be contributing to the TypeScript samples repo.

**Comment by vkarpov15** [comment]
I took a look and confirmed that adding `package-lock.json` makes installs and `@temporalio/create` much faster. I'm adding those.

Couple of other potential suggestions:

1. `npm install --no-audit` shaves off another 200ms from `npm install`. Worth it to add that in `create-project`?
2. We can get rid of eslint. That knocks `npm install --no-audit --prefer-online` from 6.2s to 4.9s on my local machine.
3. When you `npm install` in `hello-world`, `node_modules` is over 400 MB. Almost half of that is `@swc/core`. I know swc is considered to be faster and better, but perhaps there's a way to either avoid installing swc unless necessary (like https://github.com/temporalio/sdk-typescript/issues/537) or avoid installing both TypeScript _and_ swc?

```
~/Workspace/temporalio/samples-typescript/hello-world$ du -h ./node_modules/ | sort -rh | head -10
407M	./node_modules/
178M	./node_modules/@swc
89M	./node_modules/@swc/core-linux-x64-musl
89M	./node_modules/@swc/core-linux-x64-gnu
87M	./node_modules/@temporalio
83M	./node_modules/@temporalio/core-bridge
80M	./node_modules/@temporalio/core-bridge/releases
65M	./node_modules/typescript
62M	./node_modules/typescript/lib
18M	./node_modules/@temporalio/core-bridge/releases/x86_64-unknown-linux-gnu
```

**Comment by josh-berry** [comment]
Can this now be closed?

**Comment by lorensr** [comment]
Currently takes me 7s on a fast connection, which is better than it used to be, but I think worth considering vkarpov's last comment. 

Also the lockfiles were subsequently removed—there was a reason, but I forget it.

**Comment by mjameswh** [comment]
Gitting package-lock.json may help, but it adds non negligeable maintenance burden and would only cover some cases, ie. requires correct version of Node and NPM, not using pnpm or yarn, correct platform, etc.

There will always be some room for improvement on this, but I don't think this deserve prioritization. The current situation is quite reasonable, in line with what users would see with similar `npx @.../create` commands out there.
