### ISSUE TITLE
[Feature Request] snippet for `condition` API

### ISSUE THREAD

**Issue by sw-yx** [temporalio/samples-typescript#28]
### Is your feature request related to a problem? Please describe.

requested here 

- https://github.com/temporalio/documentation/pull/672#discussion_r725656150
- https://github.com/temporalio/documentation/pull/672#discussion_r725656621

### Describe the solution you'd like

sbnippet that reflects how we want to teach `condition`.

**Comment by lorensr** [comment]
These are both done
