### ISSUE TITLE
[Feature Request] Log Interceptor demo

### ISSUE THREAD

**Issue by sw-yx** [temporalio/samples-typescript#40]
### Is your feature request related to a problem? Please describe.

What's the recommended way to inject e.g. a winston logger into activities in the Node SDK? The documentation talks a lot about custom logging solutions for workflows and how to inject them through dependencies but it's less clear to me how to best do the same in an activity. I could obviously just inject the logger alongside other "services" (like db connections, etc.) when creating the activities but I was wondering if there was a different recommended way considering the specific mention of logging for workflows in the docs.

Roey Berman  1 day ago
There's a section about sharing dependencies in the activities docs page https://docs.temporal.io/docs/typescript/activities

docs.temporal.iodocs.temporal.io
Activities in TypeScript | Temporal documentation
@temporalio/activity NPM API reference | GitHub source

Roey Berman  1 day ago
Otherwise you can reference a global logger

Sebastian Siemssen  1 day ago
Yeah I know. I am using that approach for all sorts of services (db connections, kafka producers, etc.) but I was wondering if there are any quirks about logging because it gets a honorable mention in the workflow docs

Roey Berman  1 day ago
There's nothing special about activities

Roey Berman  1 day ago
Just use whatever you're used to in any normal nodejs app

Roey Berman  1 day ago
Curious to know what you come up with

Sebastian Siemssen  1 day ago
Cool. Thanks. Any problem with injecting the workflow activity context into the logger default metadata so I can serialize that into my log stream?

Sebastian Siemssen  1 day ago
I find the idea interesting of dynamically logging more verbosely if it's a retry, etc.

Sebastian Siemssen  1 day ago
https://typescript.temporal.io/api/interfaces/activity.info/

typescript.temporal.iotypescript.temporal.io
Interface: Info | Temporal Node.js SDK API Reference
activity.Info

Sebastian Siemssen  1 day ago
Btw. thanks for the super responsive support in here (and on a sunday nonetheless)
:slightly_smiling_face:
1

Roey Berman  1 day ago
Another thing you might want to do is use activity inbound interceptor with node's asynclocalstorage to create a logger with the relevant activity context

Roey Berman  1 day ago
Interceptors are like middleware so you can automatically log any activity call

Roey Berman  1 day ago
See example here https://docs.temporal.io/docs/typescript/interceptors#interceptor-examples

docs.temporal.iodocs.temporal.io
Interceptors in TypeScript SDK | Temporal documentation
Interceptors are a mechanism for users to modify inbound and outbound SDK calls.

Roey Berman  1 day ago
Just note that the sample refers to workflow outbound and not activity inbound so it's not exactly what you want

Sebastian Siemssen  1 day ago
Cool stuff. Thanks!

Roey Berman  2 hours ago
@Shawn Wang worth adding a sample to show this + docs?

Shawn Wang  2 hours ago
nice.. whats the benefit of using interceptor to log vs just share logger dependency? not super clear to me

Shawn Wang  2 hours ago
just so the logging code doesnt clutter up every activity? (edited) 
New

Roey Berman  1 hour ago
No, it's so the logger has additional context about the current activity

Roey Berman  1 hour ago
Something like this: https://github.com/winstonjs/winston#creating-child-loggers

**Comment by lorensr** [comment]
This sample uses interceptors to log: https://github.com/temporalio/samples-typescript/tree/main/instrumentation
