### ISSUE TITLE
[Feature Request] On pre-commit, only copy and prompt when needed

### ISSUE THREAD

**Issue by lorensr** [temporalio/samples-typescript#45]
### Is your feature request related to a problem? Please describe.

Currently, we prompt contributors every time they commit:

```
This will overwrite any changes made to config files in samples (like hello-world/tsconfig.json).
Proceed? [Y/n] y
Copying config files from .shared/ to samples... done.
```

And we copy all shared files to all dirs.

### Describe the solution you'd like

We could only prompt when they've edited config files that are about to be overwritten (by checking with git to see if there are local changes). Similarly, we could also only copy files from `.shared/` that have changed, or to dirs that are new.

**Comment by sw-yx** [comment]
eslint also frequently hangs on my computer when i run it locally :(
