### ISSUE TITLE
[Bug] nextjs-ecommerce-oneclick sample wont run on Windows without renaming

### ISSUE THREAD

**Issue by yoDon** [temporalio/samples-typescript#96]
### Describe the bug

There is an issue (https://github.com/temporalio/sdk-typescript/issues/450) with the typescript SDK that prevents projects from launching on Windows if the name of the project folder starts with the letter `n`. This issue currently impacts the `nextjs-ecommerce-oneclick` sample.

You can work around this issue by renaming your local copy of the folder to something that doesn't start with the letter `n`, like `ecommerce-oneclick` instead of `nextjs-ecommerce-oneclick`.

### Environment/Versions

Impacts Windows only (does not impact WSL)

**Comment by mjameswh** [comment]
Fixed in temporalio/sdk-typescript#619.
